### ISSUE TITLE
[0.2.0] Windows client history not working

### ISSUE THREAD

**Issue by modem7** [GimmerBot/Gimmer#3]
Within the windows client, history is not saved accurately. 

Chose this history entry:
![capture](https://user-images.githubusercontent.com/4349962/40134180-93fe0e10-5939-11e8-8850-e996c304d3ea.JPG)

Got this result:
![capture2](https://user-images.githubusercontent.com/4349962/40134197-9fb65b4a-5939-11e8-84bd-0ef4fbe5f7ba.JPG)

**Comment by muzkle** [comment]
Hi @modem7 , after looking at how it works, I'll try to explain this issue for you.

When you make some backtests, a history is generated as per your image 1. 
The second image will always display the last backtest results.

Once you click apply settings, only the settings are applied to the strategy to be tested, that results remains because it's from the last backtest. If you run a new backtest with those applied settings, those results will be changed to this last backtest.

Let us know if you got it, or if there's still any questions ok?

**Comment by modem7** [comment]
@muzkle - If that's the case, it might be worthwhile changing things round so that the history occurs with each click on the backtest. 

There are many circumstances where we won't save the settings until we have refined them to a suitable backtest level, once we are happy with things, only then would we click save. 

Might be worthwhile re-opening and re-labelling as a feature request rather than a bug if it's the current expected result
