### ISSUE TITLE
Hull Moving Average with three indicators

### ISSUE THREAD

**Issue by johnyqi** [GimmerBot/Gimmer#4]
At the moment HMA has only one possible value, would be nice to have three.

**Comment by swampibboy** [comment]
agreed. a fast , slow and signal HMA would be awesome , like wise the availability to turn off the signal line would be also be a good feature, leaving the indicator to only trigger trades when the slow and fast cross rather than having to wait for the fast and slow to be above the signal to buy and under to sell !!!
