### ISSUE TITLE
[Improvement] Show more detail about when/where trade was placed

### ISSUE THREAD

**Issue by keithfawcett** [GimmerBot/Gimmer#58]
It would be nice to have more detail about when/where trade was placed in the list of transactions (e.g. May 20th 18 02:33:01 @ 0.0004500)

![image](https://user-images.githubusercontent.com/592055/40581520-fc56125e-6128-11e8-90c1-c56ae8b41450.png)

**Comment by muzkle** [comment]
Hi @keithfawcett ,

As this issue is pretty much the same as the number #57 , it has been fixed by adding the complete date and time as you can check on the image below.
Once you test it with the next release, let us know if it's working.

Thanks for your support.

![buy-sell-fix](https://user-images.githubusercontent.com/16977637/40628324-af11c42a-629a-11e8-85a6-d3632d9a1b7c.PNG)

**Comment by keithfawcett** [comment]
This is now working.

**Comment by Flllexa** [comment]
Thanks man!! ;)
